AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation StackSet with S3 bucket

Resources:
  MyS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "terraform-stack-set-sample-${AWS::AccountId}"
      VersioningConfiguration:
        Status: "Enabled"
